name: Compile and jar Java Smart Client
on:
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Compile
          working-directory: ./SmartClient_Java/src
          run: |
            $JAVA_HOME_17_X64/bin/javac -cp ../lib/* -d ../bin @srcfiles.list
        - name: Jar
          working-directory: ./SmartClient_Java/bin
          run : |
            $JAVA_HOME_17_X64/bin/jar cmf ./Manifest.mf dbcsc.jar ./*
        - name: Artifact
          uses: actions/upload-artifact@v3
          with:
            name: DBCSC
            path: |
              SmartClient_Java/bin/dbcsc.jar
